- name: Variables
  hosts: local
  connection: local
  vars:
    NAME: "Anji Yarra"
    FROM: "Bhimavaram"
    Profession: "Software Engineer"
  tasks:
  - debug:
      msg: "Hi, I'm {{NAME}}, a {{Profession}} from {{FROM}}"